language: python

python:    

 - "3.6"

 

services:

  - postgres

install:    

 - pip install -r requirements.txt

 - pip install codeclimate-test-reporter

 

before_script:


  - psql -c "create database store;" -U postgres
  - psql -c "create database store_test;" -U postgres

#   - nosetests --with-coverage


script:    

 

#  -  python -m pytest --cov=

 - coveralls

 

after_success:

 - coveralls

 - codeclimate-test-reporter

cache: pip 
