language: python

python:    

 - "3.7-dev"

 

services:

  - postgres

install:    

 - pip install -r requirements.txt

 - pip install codeclimate-test-reporter

 

before_script:

  - psql -c "create database store_test;" -U postgres

  # - psql -c "create user postgres;" -U postgres

script:    

 

 -  python -m pytest --cov=app/api/v2

 - coveralls

 

after_success:

 - coveralls

 - codeclimate-test-reporter

cache: pip 