language: python

python:    

 - "3.6"

 

services:

  - postgres

install:    

  
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
  - pip install coverage
  - pip install coveralls
  

before_script:


  - psql -c "create database store;" -U postgres
cache: pip 

script:    

#   - coverage run --source=app -m pytest && coverage report

 

after_success:

 - coveralls

 - codeclimate-test-reporter

cache: pip 
before_script:
 
 - psql -c 'create database teststore;' -U postgres
script:
#  - coverage run --source=app -m pytest && coverage report 

after_script:
 - coveralls 
 - codeclimate-test-reporter
after_success:
- coveralls
