language: python

python:    
 - "3.6"

services:
  - postgres

install:    
  - pip install -r requirements.txt
  # - pip install codeclimate-test-reporter
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --source app,tests,instance -m pytest
  - python -m coverage report -m

before_script:
  - psql -c "create database store;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres

env:
- DATABASE_URL= "dbname='store_test' host='localhost' port='5432' user='postgres' password='root'"
 
after_success:
 - coveralls
 - codeclimate-test-reporter

cache: pip 
