language: python

python:    

 - "3.6"

 

services:

  - postgres

install:    

  
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
  - pip install coverage
  - pip install coveralls
  
  

 

before_script:


  - psql -c "create database store;" -U postgres


script:    

 - coveralls

 

after_success:

 - coveralls

 - codeclimate-test-reporter

cache: pip 
